score_informed:
  method: note_editor
  params:
    arch: conformer          # transformer / conformer
    d_model: 128
    n_layers: 2
    n_heads: 4
    dropout: 0.1
    alpha: 0.2
    mask_outside_onset: true


# score_informed:
#   method: note_editor
#   params:
#     arch: conformer        # transformer / conformer
#     d_model: 128
#     n_layers: 2
#     n_heads: 4
#     dropout: 0.1
#     alpha: 0.2
#     token_features:
#       use_vel: true
#       use_vel_logits: true
#       use_dur_runlen: true
#       use_polyphony: true
#     position_encoding: sinusoidal
#     mask_outside_onset: true
