_wandb:
    value:
        cli_version: 0.19.3
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 5
                - 50
                - 53
                - 55
                - 100
            "2":
                - 1
                - 5
                - 50
                - 53
                - 55
                - 100
            "3":
                - 13
                - 14
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.3
            "8":
                - 5
            "12": 0.19.3
            "13": linux-x86_64
dataset:
    value:
        maestro_dir: ../Dataset/maestro-v3.0.0
        maps_dir: ../Dataset/MAPS
        smd_dir: ../Dataset/SMD
        test_h5: /media/mengh/SharedData/zhanh/202510_hpt_data/workspaces/hdf5s/smd
        test_set: smd
        train_h5: /media/mengh/SharedData/zhanh/202510_hpt_data/workspaces/hdf5s/maestro
        train_set: maestro
exp:
    value:
        batch_size: 12
        ckpt_file: ""
        ckpt_iteration: ""
        cuda: true
        decay: true
        eval_iteration: 10000
        learning_rate: 0.0001
        mini_data: false
        num_workers: 12
        optim: adam
        random_seed: 86
        reduce_iteration: 10000
        run_infer: single
        save_iteration: 10000
        total_iteration: 120000
        workspace: /media/mengh/SharedData/zhanh/202510_hpt_data/workspaces
feature:
    value:
        audio_feature: logmel
        augmentor: null
        begin_note: 21
        classes_num: 88
        fft_size: 2048
        frames_per_second: 100
        hop_seconds: 1
        max_note_shift: 0
        sample_rate: 22050
        segment_seconds: 10
        velocity_scale: 128
loss:
    value:
        huber_delta: 0.1
        kim_loss_alpha: 0.5
        loss_type: score_inf_custom
        use_huber: true
        w_bce: 0.5
        w_delta: 0.01
        w_huber: 1
        w_l1: 1
model:
    value:
        hppnet_model_size: 128
        input2: onset
        input3: null
        kim_condition: frame
        pretrained_checkpoint: /media/datadisk/home/22828187/zhanh/202510_hpt_data/workspaces/checkpoints/FiLMUNetPretrained+frame/1000000_iterations.pth
        type: hpt
post:
    value:
        frame_threshold: 0.3
        offset_threshold: 0.3
        onset_threshold: 0.3
        pedal_offset_threshold: 0.2
        post_processor_type: regression
score_informed:
    value:
        method: bilstm
        switch_iteration: 100000
        train_mode: joint
wandb:
    value:
        comment: mel128
        log_velocity_interval: 10000
        name: logmel-hpt-bilstm-score_inf_custom-k0.5-l11.0-b0.5-d0.01-uhTrue-wh1.0-hd0.1-extonsetNone-sr22050
        project: 202602_smc
